name: Feature request
description: Suggest an idea or a new controller / game to support
labels: [enhancement]
body:
  - type: textarea
    id: idea
    attributes:
      label: What would you like?
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: Why is it useful? (game, emulator, use case)
